version: '3.5'

services:
  postgres:
    image: postgres:alpine
    container_name: sales-api-postgres
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
    ports:
      - '5432:5432'
