import 'reflect-metadata';
import express, { NextFunction, Request, Response } from 'express';
import cors from 'cors';
import routes from './routes';
import AppError from '../errors/AppError';
import '../typeorm';

const app = express();

app.use(cors());
app.use(express.json());

app.use(routes);

//creating middleware to capture all errors generated by the app
//and using the AppErrors class to create a costumizable error message for the frontend
app.use((error : Error,
  request : Request,
  response : Response,
  next: NextFunction)=>{

     //every error generated by the application will be handled by AppError class
    if(error instanceof AppError)
    {
      return response.status(error.statusCode).json({
        status: 'error',
        message: error.message
      })
    }

    //if error if not an instance of AppError, then its an unknown error
    return response.status(500).json({
      status: 'error',
      message: 'Internal server error'
    });

});

app.listen(7777,()=>{
  console.log("server started on port 7777");
});


